### ISSUE TITLE
Include mappings to EFG

### ISSUE THREAD

**Issue by tucotuco** [tdwg/chrono#11]
Could use help with this to get it right. Is this something @falkogloeckler can help with?

**Comment by lbrensk** [comment]
@falkogloeckler @tucotuco I made the mappings. Please see here: [https://docs.google.com/spreadsheets/d/13KrFJE4nIYxZnJ07Q0DumrhadtUVHGsJI1ioq2TAMfE/edit#gid=0](https://docs.google.com/spreadsheets/d/13KrFJE4nIYxZnJ07Q0DumrhadtUVHGsJI1ioq2TAMfE/edit#gid=0) You should be able to make comments on the Google document, or replies here will be fine. I think most of the mappings seem fairly straightforward, but I am not familiar with how the Identifiers work in ABCD-EFG. It would be helpful for someone more familiar with ABCD-EFG to take a look and see if they agree with the mappings. Links to the different standards and their definitions are in the top column label.

**Comment by falkogloeckler** [comment]
Thanks @lbrensk! I added a view comments.
Basically, there are always multiple options in ABCD-EFG to accommodate the information. In most cases I'd opt for using the complex type `StratigraphicMeasurementOrFact` under the concept of `ChronostratigraphicAttribution`. So, most of my comments in the GDoc are related from this perspectice.

**Comment by tucotuco** [comment]
Thank you both. I have made the additions based on your findings and we will incorporate them in new versions of all affected terms.

**Comment by tucotuco** [comment]
Done.
