### ISSUE TITLE
Change term - materialDatedID

### ISSUE THREAD

**Issue by tucotuco** [tdwg/chrono#13]
## Change term

* Submitter: John Wieczorek
* Justification (why is this change necessary?): consistency
* Proponents (who needs this change): Everyone

Proposed new attributes of the term:

* Organized in Class: ChronometricAge

Propose that the term be deprecated before public review in favor of chronoiri:materialDated, which already has the correct semantic definition.

**Comment by tucotuco** [comment]
Retracting the issue as it is a bigger one that already exists in DwC because of higherGeographyID and various ID terms in the Taxon class, and no one in the community has suggested changing that. Rather than complicate the proposal and introduce an untested change (second namespace in the GBIF extension), I prefer to keep the proposal as is. Closing.

**Comment by timrobertson100** [comment]
Thanks, John.

For the record, I agree with this. The *ID terms need attention but I don't think that bigger can of worms should block progress here.
