### ISSUE TITLE
Handling of IRI values

### ISSUE THREAD

**Issue by tucotuco** [tdwg/chrono#18]
Is there a mechanism to supply IRI values for  chrono:chronometricAgeDeterminedBy, either with an id term chrono:chronometricAgeDeterminedByID or an IRI namespace chronoiri:chronometricAgeDeterminedBy?  Such a mechanism would be needed to allow an RDF representation to express a list of chronometric age determiners as repeated id terms, each pointing to a determiner agent by  ORCID or other agent identifier.

_Originally posted by @chicoreus in https://github.com/tdwg/chrono/issues/15#issuecomment-732198397_

**Comment by tucotuco** [comment]
The mechanism to supply IRI values is two-fold. One can always provide an IRI value in the chrono:chronometricAgeDeterminedBy term, though it isn't expected there. It IS expected in the chronoiri: corollary term chronoiri:chronometricAgeDeterminedBy.

**Comment by chicoreus** [comment]
Clarifying this, the handling of IRI values isn't consistent in the chrono terms.   The text of the proposal in #15 implies that an IRI term for chrono:chronometricAgeDeterminedBy would be created in a chronoiri namespace as chronoiri:chrono:chronometricAgeDeterminedBy by a change to the Darwin Core RDF guide, but the proposed vocabulary includes the alternative handlign for an IRI term in chrono:materialDatedID, which, if consistent, would be chronoiri:materialDated.   While chrono:chronometricAgeReferences  takes a pipe delimited list of identifiers for references, with the inclusion of IRI values within this pipe delimited list an explicit part of the definition.. I'd advocate for one way of handling IRI values, and making how this is to done an explicit part of the chronometric age vocabulary.  It would make sense to mint parallel chronoiri terms for each chrono term that has a logical IRI analog (at least; materialDated, chronometricAgeReferences, chronometricAgeDeterminedBy, minimumChronometricAgeReferenceSystem, maximumChronometricAgeReferenceSystem, and probably others).

**Comment by tucotuco** [comment]
In addition to documentation in the RDF Guide, we propose now to add the IRI-value terms to a section in the [ChronometricAge term list document](https://tdwg.github.io/chrono/list/#3-term-index) as is done in the [Darwin Core term list document](https://dwc.tdwg.org/list/#3-term-indices) see issue #19. Thus, there would be both the term chrono:chronometricAgeDeterminedBy and the term chronoiri:chronometricAgeDeterminedBy, each with their definitions in the normative content of the term list.

The proposed term chrono:materialDatedID is not the same as the term chronoiri:materialDated. The latter MUST have an IRI as content, the former can, but need not. It can be an identifier local to the data set. Thus, all three terms would exist. There would be no chronoiri:materialDatedID term, it would be semantically the same as chronoiri:materialDated. 

The term chrono:chronometricAgeReferences would not have a matching chronoiri: term. Instead, the distinct references would be the subject of dcterms:references relationships as explained in the RDF Guide.

**Comment by tucotuco** [comment]
Adapted from commentary elsewhere by Tim Robertson (with permission):

Note: ID terms refer to those in Darwin Core whose names end in "ID". IRI terms refer to those in or theoretically apt for the Darwin Core [IRI-value list](https://dwc.tdwg.org/list/#3-term-indices), all of which currently use the dwciri: namespace.

1. IRI guidelines as written in the [RDF Guide](https://dwc.tdwg.org/rdf/) imply their use in some RDF serialization, which may not be true of either ID terms or IRI terms.
1. DwC has wide use and further potential in DB schema design, RESTful interface design, etc. It can be impractical, or inconsistent to have to introduce a namespace in the field names (e.g., needing to encode “:” etc) to distinguish between terms with the same local name but distinct semantics.
    1. Naming things is hard, and DwC has provided a vocabulary applied to many problems that is a compromise between intuitive and inclusive for newcomers.
1. An IRI commits an ID to a domain name.
    1. Domains change, especially when dealing with private sector.
    1.  The long-term value proposition of committing to a domain is low when considering data archives that are expected to persist (e.g., a Darwin Core Archive).
1. An IRI may be impractical or against the advice/requirements of an ID issuer with respect to prepending a resolver.
    1. The DOI community has changed stance on this over time. The [current stance](https://www.crossref.org/blog/new-crossref-doi-display-guidelines-are-on-the-way/) is to show the URL, at least for display purposes.
    1. Open Digital Specimens (forthcoming TDWG TG) will use handles (DOIs probably), and redundant, local, caching infrastructure provided by Handle would be a prime reason not to prepend with resolvers. One presumes they may arrive at the conclusion that redundancy in handle resolvers is a good thing, and give guidelines to use  xx.xxx/* format identifiers rather than opting for a single resolver, to benefit from the local caching infrastructure handle provides (I would).
1. It is useful to have fields to GROUP BY or JOIN ON that have little other utility when shared over the web.
1. The format of the content of ID terms can be outside our control in specific cases, and are therefore must be considered outside our control in general. 
1. Many Darwin Core ID terms refer to instances of Darwin Core Classes, which we manage. Every Darwin Core Class has such an ID term (e.g., dwc:Event). Yet, there is a precedent in the many ID terms in Darwin Core that refer to external entities (collectionID, institutionID, datasetID, higherGeographyID, scientificNameID, nameAccordingToID, namePublishedInID) without any commitment to or convention about the Classes of those entities. In a sense they are placeholders for whatever one wants to connect to. I’m not aware that any concerns have ever been expressed about this approach. 
1. The DwC classes are also placeholders in the sense that Darwin Core does not formally bind any properties to them, nor does it relate them to each other or other classes. Let’s put our effort into renewing the TDWG domain model work. Semantic DwC went some way toward this, but I’d like to reboot to ~2008 where everyone was able to participate in sharing ideas around having a common data model.

**Comment by baskaufs** [comment]
Comment on the above. For what it's worth, an IRI does not have to include a domain name. There are non-http IRIs, such as urn's that were once in vogue but are not very commonly used any more. I believe that part of the idea behind URNs were to avoid the instability caused by including a domain name, but one of the reasons they didn't get used was because people minted them and then nobody could figure out what they meant because there was no dereferencing mechanism. It's also difficult to make sure that a non-http identifier is globally unique if there is no issuing authority. So not having a domain name in the identifier is a double-edged sword if you actually want identifiers to be globally unique. Maybe we've just given up on that?

Part of the solution to this is to create identifiers that contain domain names (or can be mapped to domain names) that are stable. DOIs, ORCIDs, VIAFs, and Wikidata QIDs seem to meet that requirement at least so far.

**Comment by tucotuco** [comment]
> In addition to documentation in the RDF Guide, we propose now to add the IRI-value terms to a section in the [ChronometricAge term list document](https://tdwg.github.io/chrono/list/#3-term-index) as is done in the [Darwin Core term list document](https://dwc.tdwg.org/list/#3-term-indices) see issue #19. Thus, there would be both the term chrono:chronometricAgeDeterminedBy and the term chronoiri:chronometricAgeDeterminedBy, each with their definitions in the normative content of the term list.
> 

The IRI terms have been added to the term list document and to the Quick Reference Guide with commit 33a132982e5f6d83dd368b822b3766d23ff00a2b.

**Comment by tucotuco** [comment]
Passed public review.

**Comment by tucotuco** [comment]
Ratified! Closing.
