### ISSUE TITLE
Add IRI-value terms section to term list document

### ISSUE THREAD

**Issue by tucotuco** [tdwg/chrono#19]
I see the statement "Once ratified, the Darwin Core RDF Guide will be updated to include the IRI versions of appropriate terms from this vocabulary, in the chronoiri: namespace, for use in RDF (e.g., as Linked Open Data)." in [the issue above](https://github.com/tdwg/chrono/issues/18), however, this feels like something that should be an explicit part of the chrono vocabulary, not relegated to the RDF guide, and some possible future action on the RDF guide.

_Originally posted by @chicoreus in https://github.com/tdwg/chrono/issues/15#issuecomment-732207968_

**Comment by chicoreus** [comment]
See also comment https://github.com/tdwg/chrono/issues/18#issuecomment-733901803 where I raise the concern that IRI values are handled in three different ways in the current proposed chronometric age vocabulary (with an ID term, with an assumed to be created chronoiri term, and within a pipe delimited list).   Handling should be consistent, part of the vocabulary, and should not depend on the Darwin Core RDF guide.

**Comment by tucotuco** [comment]
It seems that it is not clear that the RDF Guide additions will accompany updating the final versions of documents associated with this vocabulary enhancement. They will. It is part of the normative documentation of Darwin Core, of which this vocabulary will form a part if ratified. To date, all treatment of IRI terms is via the RDF Guide. To do otherwise would be a fundamental change to how Darwin Core is documented. That isn't out of the question if it will somehow be of benefit, but that change should be separate from this vocabulary enhancement review, as it has much broader implications and is not the core problem of this specific task group.

**Comment by chicoreus** [comment]
@tucotuco  Super.  I'd advocate for a specific enumeration of the proposed chronoiri terms and the language to be added to the RDF guide.   The chronometric age vocabulary will still need a normative cross reference to the Darwin Core RDF guide, and the three internally inconsistent methods for handling identifiers within the chrono: vocabulary need to be addressed.

**Comment by chicoreus** [comment]
A complexity to consider that may not be a simple mapping of a chrono: term onto a chronoiri: term.  @wouteraddink crossreferenced the timescale ontology in #15, and this ontology uses the W3C time vocabulary, thus, consideration needs to be given to how time:Interval (and/or other time: terms) would relate to one or more chronoiri terms.  time:Interval might map naturally onto a chronoiri:chronometricAge (Range) term (not present in chrono:, which would carry the information of chrono:maximumChronometricAge and chrono:minimumChronometricAge.  Thinking about how IRI values might be mapped onto chrono:maximum/minumumChronometricAge raises an issue that touches directly on the set of terms in chronoiri, and isn't a simple mapping of a chrono term onto a chronoiri term in the way that the Darwin Core RDF guide discusses 1:1 dwciri analogs for dwc terms...

**Comment by tucotuco** [comment]
I agree @chicoreus. The documentation is missing a section for IRI-value terms in the [term list document](https://tdwg.github.io/chrono/list/#3-term-index), just as they are for Darwin Core in its [term list document](https://dwc.tdwg.org/list/#3-term-indices) under the same heading. These all need to be added. Changing the issue title to reflect that task.

**Comment by tucotuco** [comment]
Another relevant comment from the public commentary...

materialDatedID also indicates that chrono and chronoiri need to be explicitly brought into and dealt with within the chronometric age vocabulary.   chrono::chronometricAgeDeterminedBy, chronoiri::chronometricAgeDeterminedBy, and chronoiri:materialDatedID (but no chrono:materialDatedID), sound like they need to be explicitly discussed in the vocabulary.  There are likely chronoiri terms that can relate to time: terms (time:timeTRS, thors;ReferenceSystem, time:interval, time:instant, etc),  e.g. chronoiri:maximumChronometricAgeReferenceSystem/minimumChronometricAgeReferenceSystem might relate closely with time:timeTRS and thors:ReferenceSystem (or not, I haven't looked closely - but more attentions needs to be given to potential chronoiri terms and their definitions).

_Extracted from original post by @chicoreus in https://github.com/tdwg/chrono/issues/15#issuecomment-732249855_

**Comment by tucotuco** [comment]
IRI terms added to term list and Quick Reference Guide documents as of commit 33a132982e5f6d83dd368b822b3766d23ff00a2b.

**Comment by tucotuco** [comment]
Ratified! Closing.
