### ISSUE TITLE
Change term - maximumChronometricAge, maximumChronometricAge

### ISSUE THREAD

**Issue by tucotuco** [tdwg/chrono#22]
## Change term

* Submitter: John Wieczorek (from public commentary)
* Justification (why is this change necessary?): clarity
* Proponents (who needs this change): Everyone

**Originally proposed new attributes of the term**:

* **Organized in Class**: ChronometricAge
* **Term names**: maximumChronometricAge, minimumChronometricAge
* **Definition of maximumChronometricAge**: Upper limit for the age (the earliest possible age) of a specimen as determined by a dating method.
* **Definition of minimumChronometricAge**: Lower limit for the age (the latest possible age) of a specimen as determined by a dating method.
<br>

**Updated (current) proposed new attributes of the terms**:
* **Organized in Class**: ChronometricAge
* **Term name**: earliestChronometricAge
* **Label**: Earliest Chronometric Age
* **Definition**: The maximum/earliest/oldest possible age of a specimen as determined by a dating method.
* **Comments**: The expected unit for this field is years. This field, if populated, must have an associated earliestChronometricAgeReferenceSystem.
* **Example**: `100`
<br>

* **Term name**: latestChronometricAge
* **Definition**: The minimum/latest/youngest possible age of a specimen as determined by a dating method.
* **Comments**: The expected unit for this field is years. This field, if populated, must have an associated latestChronometricAgeReferenceSystem.
* **Example**: `27`
<br>

The change of term names also requires changes to the corresponding terms for age reference systems.
* **Term name**: earliestChronometricAgeReferenceSystem
* **Definition**: The reference system associated with the earliestChronometricAge.
* **Comments**: Recommended best practice is to use a controlled vocabulary.
* **Examples**: `kya`,`mya`,`BP`,`AD`,`BCE`,`ka`,`Ma`,`Ga`
<br>

* **Term name**: latestChronometricAgeReferenceSystem
* **Definition**: The reference system associated with the latestChronometricAge.
* **Comments**: Recommended best practice is to use a controlled vocabulary.
* **Examples**: `kya`,`mya`,`BP`,`AD`,`BCE`,`ka`,`Ma`,`Ga`

**Comment by tucotuco** [comment]
@tucotuco  in reference to oldest/youngest: 
> Would usage comments be sufficient to cover this, or is it necessary to be in the definition?

By analogy to (and for consistency with) the dwc:gGeologicalContext terms, where earlyest and latest are used in the definitions for terms which can take temporal concept values  "latest possible geochronologic", "earlyest possible geochronologic", the normative definition feels like the place to do this, and for consistency earlyest and latest may be the words to use instead of oldest and youngest.

_Originally posted by @chicoreus in https://github.com/tdwg/chrono/issues/15#issuecomment-733941307_

**Comment by visead** [comment]
Another factor to consider is that "maximum, minimum, upper, and lower" change their directionality when used in a future modelling context (eg. climate scenario future species ranges based on fossil distributions). If users cite terms correctly this should not be a problem, but earliest/latest or oldest/youngest reduces the risk.

**Comment by lbrensk** [comment]
I agree that adding "oldest" and "youngest" to these definitions would be the clearest way to state what is intended and avoid errors in data entry or interpretation.

**Comment by lbrensk** [comment]
This comment is to summarize email correspondence with Denné Reed (@dennereed). For the sake of clarity and full transparency in the public review process, we want to make sure all relevant correspondence is recorded on GitHub.

Email from Denné Reed on 13 Jan 2021: 
> Revise the definition, examples and/or names of maximumChronometricAge and minimumChronometricAge to clarify ambiguity regarding their intended meaning. From the name I take maximumChronometrixAge to refer to the oldest age associated with an occurrence and the minimumChronometricAge to represent the younger/most recent age associated with an occurrence. The definition for maximumChronometricAge says “Upper limit for the age” which for most geologists could (would) mean the youngest (rather than the oldest) age because in geological context upper is younger. Similarly for minimum, the lower limit would be the older. The confusion is heightened by the examples, 27 given for maximum and 100 given for minimum. I think using the words “oldest” and “youngest” in the definitions would go furthest toward clarifying.

Email reply from John Wieczorek (@tucotuco) on 19 Jan 2021:
> This issue was raised on GitHub and has been addressed here: https://github.com/tdwg/chrono/issues/22 

Email reply Denné Reed on 25 Jan 2021: 
> Regarding the definition (and examples) for minimum/maximumChronometricAge, I agree that the updated definitions presented in GitHub Issue #22 is an improvement though I maintain that somewhere including “oldest” and “youngest” in the definitions would do the most to relieve ambiguity and assure that the terms are applied correctly and consistently. I agree with the preference to use “earliest” and “latest" to maintain consistency with the definitions in the GeologicalContext, however I find the definitions in GeologicalContext suboptimal and would prefer that the definitions in the ChronometricAge extension avoid the same limitations. The definitions in the Geological Context use “earliest” and “latest” both in the term name and the definition, which does little to providing clarity or additional understanding. I would argue GeologicalContext would also benefit from including “oldest” and “youngest” in the definitions. So repeating the pattern in the ChronometricAge extensions for the sake of consistency seems a lost opportunity. Hopefully the examples in ChronometricAge could offer clues, where those in GeologicalContext do not. Would it be inappropriate or burdensome to revise the definition for maximumChronometricAge for example to “Upper limit for the age (the earliest/oldest possible age) of a specimen as determined by a dating method” And use 100 in the example?  Also if we’re emphasizing consistency, should this term be earliestChronometricAge?

Email reply from John Wieczorek on 25 Jan 2021:
> I understand what you were getting at much better now with the rest of the context, and agree that this is a nice opportunity to not make the same omission of clarity now when we have the opportunity to avoid that. We will alter the proposal for the min/max ages and include your commentaries and responses to them in the GitHub issue for that. We don't anticipate any issues with these changes, as they are not semantic, but rather only clarifying. 

Email reply Denné Reed on 25 Jan 2021: 
>That all sounds great. Thanks for addressing the concerns and considering the suggestions. Very happy to see the progress on the ChronometricAge extension. It’s a crucial addition to Darwin Core.

**Comment by tucotuco** [comment]
The original issue text has been modified to include the updated term definitions for earliestChronometricAge, latestChronometricAge, earliestChronometricAgeReferenceSystem and latestChronometricAgeReferenceSystem.

**Comment by tucotuco** [comment]
Term changes implemented as of commit 33a132982e5f6d83dd368b822b3766d23ff00a2b.

**Comment by tucotuco** [comment]
Passed public review.

**Comment by tucotuco** [comment]
Ratified! Closing.
