### ISSUE TITLE
Change term - ChronometricAge

### ISSUE THREAD

**Issue by lbrensk** [tdwg/chrono#23]
## Change term

* Submitter: Laura Brenskelle
* Justification (why is this change necessary?): After discussion (that can be found here https://github.com/tdwg/chrono/issues/20), this definition requires clarification. This will make the intended uses of this extension more clear for data users and providers. We have also changed it to provide examples and a usage comment of when it is and is not appropriate to use the ChronometricAge extension.
* Proponents (who needs this change): Public review.

Proposed new attributes of the term:

* Organized in Class: ChronometricAge
* Term name (in lowerCamelCase): chrono:ChronometricAge
* Definition of the term: "The age of a specimen and how this age is known, whether by a dating assay, a relative association with dated material, or legacy collections information."
* Usage comments (recommendations regarding content, etc.): The ChronometricAge extension is to be used only in cases where the collection event is not contemporaneous with the time when the organism was alive in its context. Collection event information can be reported in dwc:eventDate.
* Examples: "An age range associated with a specimen derived from an AMS dating assay applied to an oyster shell in the same stratum"; "An age range associated with a specimen derived from a ceramics analysis based on other materials found in the same stratum"; “A maximum age associated with a specimen derived from K-Ar dating applied to a proximal volcanic tuff found stratigraphically below the specimen”; “An age range of a specimen based on its biostratigraphic context”; “An age of a specimen based on what is reported in legacy collections data”.
* Refines (identifier of the broader term this term refines, if applicable): N/A
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): N/A
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG, if applicable): N/A

**Comment by tucotuco** [comment]
Term changes implemented as of commit 33a132982e5f6d83dd368b822b3766d23ff00a2b.

**Comment by tucotuco** [comment]
Superseded by changes in issue #27.
