### ISSUE TITLE
New Term - materialDatedRelationship

### ISSUE THREAD

**Issue by lbrensk** [tdwg/chrono#24]
## New term

* Submitter: Laura Brenskelle
* Justification (why is this term necessary?): See https://github.com/tdwg/chrono/issues/20.
* Proponents (at least two independent parties who need this term): Public review.

Proposed attributes of the new term:

* Organized in Class: ChronometricAge
* Term name (in lowerCamelCase): materialDatedRelationship
* Definition of the term: The relationship of the materialDated to the subject of the ChronometricAge record, from which the ChronometricAge of the subject is inferred.
* Usage comments (recommendations regarding content, etc.): Recommended best practice is to use a controlled vocabulary.
* Examples: `sameAs` (cases where the subject material was completely destructively subsampled to get the ChronometricAge), `subsampleOf` (cases where part of the original specimen was extracted as the material used to determine the ChronometricAge), `inContextWith` (cases where the ChronometricAge is inferred from materialDated, such as sediments or cultural objects, in related temporal context), `stratigraphicallyCorrelatedWith` (cases where the ChronometricAge is inferred from materialDated in a stratigraphically correlated context).
* Refines (identifier of the broader term this term refines, if applicable):
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable):
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG, if applicable):

**Comment by chicoreus** [comment]
Consider adding an additional example value:  "stratigraphicallyCorrelatedWith" (cases where the Chronometric Age is inferred from materialDated in a stratigraphically correlated context).  Or something along that line that allows the distinction between a dated sample from the immediate context of an excavation/borehole/outcrop/etc. and a dated sample from the same horizon in a different excavation/borehole/outcrop/etc, that is placed in the same horizon by stratigraphic correlation.

**Comment by tucotuco** [comment]
Added the recommended additional example in the term change proposal above.

**Comment by tucotuco** [comment]
New term included in all documents as of commit 33a132982e5f6d83dd368b822b3766d23ff00a2b.

**Comment by tucotuco** [comment]
Passed public comment.

**Comment by tucotuco** [comment]
Ratified! Closing.
