### ISSUE TITLE
Publish ratified version of extension to GBIF extensions

### ISSUE THREAD

**Issue by tucotuco** [tdwg/chrono#26]
Deprecate the [review version of the extension](https://tools.gbif.org/dwca-validator/extension.do?id=http://rs.tdwg.org/chrono/terms/ChronometricAge) and create a new one that makes it very clear that it is a TDWG-ratified vocabulary.

**Comment by tucotuco** [comment]
Updated post-review version added in commit e3f146e2c772f16922c650b14948b322446106df.

**Comment by tucotuco** [comment]
Pull request created. https://github.com/gbif/rs.gbif.org/pull/64

**Comment by tucotuco** [comment]
Once this is live in production and tested available via IPT, alert TDWG Exec so that it can be announced.

**Comment by timrobertson100** [comment]
We're in the final stages https://github.com/gbif/rs.gbif.org/issues/65
This test is only to verify it display's as expected before that exact file is copied into production.

**Comment by tucotuco** [comment]
Done.  Closing.

https://tools.gbif.org/dwca-validator/extension.do?id=http://rs.tdwg.org/chrono/terms/ChronometricAge
https://github.com/gbif/rs.gbif.org/blob/master/extension/dwc/ChronometricAge_2021-03-27.xml
