### ISSUE TITLE
Change term - ChronometricAge

### ISSUE THREAD

**Issue by smrgeoinfo** [tdwg/chrono#27]
## Change term

* Submitter: Stephen Richard
* Justification:  Definition given on the term chrono:ChronometricAge "The age of a specimen or related materials that is generated from a dating assay." is not a definition unless 'age' is defined. In the abstract we have this: "chronometric ages - the processes and results of an assay or other analysis used to determine the age of a sample." If a thing is a process and a result, it must be the result of a process or event. These are perduants, temporal things. Interpreting probable intention, the statement reduces to "an age is a result used to determine an age". This is circular.
Specimens are endurants, they only have temporal position indirectly through their participation in events; only the events can be located in time.

* 
* Proponents: anyone trying to understand what you mean.

Proposed new attributes of the term:

* Organized in Class: ChronometricAge
* Term name: chronometric age: 
* Definition of the term: A temporal position assigned to an event in the history of a specimen.
* Usage comments :
The age assignment is the result of some procedure that might involve analysis of the specimen as well as observed or inferred relationships to other analyzed materials.  Typically the event of interest is when the sampled object originated, but what constitutes 'origin' will depend on the kind of sample. For a fossil, the origin event might be considered the life of the organism that was fossilized, for an archeological artifact when the item was manufactured, for a sedimentary rock when the sediment was deposited, for a metamorphic rock when it was metamorphosed.  Other events in the history of a specimen might also be of interest and assigned chronometric ages. 

   ##### Necessary properties:
    -- the event that is assigned a temporal position
    -- the temporal reference system used to assert temporal position
    -- the assigned age value (instant or interval)
   ##### other important properties
    -- method used to assign age
    -- uncertainty 

* Examples: 
* Refines (identifier of the broader term this term refines, if applicable):
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable):
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG, if applicable):

**Comment by lbrensk** [comment]
During the public review process, the definition of ChronometricAge has changed from the one you referenced in your initial comment. You can find the updated definition, comments, and examples here: https://tdwg.github.io/chrono/terms/#chronometricage Please take a look and let us know if the updated term addresses your concerns or not.

**Comment by tucotuco** [comment]
Issues that results in the changes to the ChronometricAge definition, usage notes and examples can be found in https://github.com/tdwg/chrono/issues/23 and https://github.com/tdwg/chrono/issues/20.

**Comment by smrgeoinfo** [comment]
Interesting, I was looking a what looks like exactly the page you link to above where I got that definition...  
The new definition:
- 'The age of a specimen'  this hasn't changed and is the crux of the issue,  still doesn't define what 'age' means, 
- 'how this age is known' is metadata about the age assignment. That should be part of the content model for how an age is represented, but ?does it help define what 'age' means....? 
- 'whether by a dating assay, a relative association with dated material, or legacy collections information.'  Not part of a definition -- should be in the notes, as in my suggestion (although I phrase it differently).

**Comment by robgur** [comment]
Stephen, hi.  Thanks for the comments here.  We understand your concern about not defining age in detail. We propose the following alternate definition to address that concern: "The age (a reference to a range in the continuum of time) of a specimen and how this age is known, whether by a dating assay, a relative association with dated material, or legacy collections information." We feel that the examples of how an age might be determined are important to retain in the definition, as this was the consensus solution to previous concerns about the definition and we dearly want to avoid getting into an endless loop in which consensus cannot be reached.

**Comment by smrgeoinfo** [comment]
I don't think what I'm saying is getting communicated, but this is not a good venue to sort it out. I'm just suggesting you need a definition for what you mean by 'age'. I don't think "An age is a reference to a range in the continuum of time" is a good definition, but if it works for your community I'm not going to argue.

**Comment by tucotuco** [comment]
Hi Stephen,

You are right, it seems we are all talking past each other. How would you
define age? We thought about going to the extreme of tying it to , but that
would definitely take it farther from real understanding in our community,
for which it wasn't necessary to elaborate on age at all, because the only
possible source of confusion would be the age of an organism in its own
lifespan, but that is clearly not the meaning based on any of the context
of the Class or its properties.

Cheers,

John

**Comment by tucotuco** [comment]
Sorry, I omitted something there - tying the definition to
https://www.w3.org/TR/owl-time/#time:TemporalPosition.

**Comment by smrgeoinfo** [comment]
Definition of the term: A [temporal position](https://www.w3.org/TR/owl-time/#time:TemporalPosition) assigned to an event in the history of a specimen.
Usage comments : (see [above](https://github.com/tdwg/chrono/issues/27#issue-807404145) ).

If the concept of a temporal position and the idea that physical objects don't have temporal positions directly are too difficult, perhaps the ontologic grounding could be in the background-- maybe 'expert notes'? or something.  If the only concern is the time interval during which an organism (individual or species?) was alive, then maybe simplify to "The time interval during which an organism was alive". This would be a subClass of a more generic chronometricAge that could be anchored to any event.

**Comment by tucotuco** [comment]
@ smrgeoinfo The Task Group Core members have considered and appreciate your perspective and comments. I think our target is actually the more generic one anchored in the Event. We offer an alternative term change proposal that distinguishes ChronometricAge from a TemporalPosition by virtue of there being available evidence, and relegate the rest of what we had in the definition to the usage notes encapsulated in the Comments attribute, which in Darwin Core are not normative and therefore have more flexibility for community-based evolution without the full standards ratification process.

Proposed new attributes of the term:

* Term name (in lowerCamelCase): chrono:ChronometricAge
* Definition of the term: "An approximation of a temporal position (in the sense conveyed by https://www.w3.org/TR/owl-time/#time:TemporalPosition) that is supported via evidence."
* Previous definition: "The age of a specimen and how this age is known, whether by a dating assay, a relative association with dated material, or legacy collections information."
* Usage comments (recommendations regarding content, etc.): "The age of a specimen and how this age is known, whether by a dating assay, a relative association with dated material, or legacy collections information."
* Previous usage comments: "The ChronometricAge extension is to be used only in cases where the collection event is not contemporaneous with the time when the organism was alive in its context. Collection event information can be reported in dwc:eventDate."
* The previous usage comments are better suited to the dc:description of the purpose of the extension within the Darwin Core extension's XML specification file.
* Examples: "An age range associated with a specimen derived from an AMS dating assay applied to an oyster shell in the same stratum"; "An age range associated with a specimen derived from a ceramics analysis based on other materials found in the same stratum"; “A maximum age associated with a specimen derived from K-Ar dating applied to a proximal volcanic tuff found stratigraphically below the specimen”; “An age range of a specimen based on its biostratigraphic context”; “An age of a specimen based on what is reported in legacy collections data”.
* Refines (identifier of the broader term this term refines, if applicable): N/A
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): N/A
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG, if applicable): N/A

**Comment by smrgeoinfo** [comment]
I think the proposed new definition is MUCH better!

**Comment by tucotuco** [comment]
So do we, and we thank you for the impetus to make it so. Do we have a
consensus then? If we do, we can reset the review clock for 30 days from
today.

**Comment by robgur** [comment]
+1

**Comment by robgur** [comment]
Hi everyone -- I think it appears we reached consensus. Stephen, if that
is not the case, can you let us know?  We just want to be sure to reset the
clock on timing for further public comment with the new term in place.
Best, Rob

**Comment by smrgeoinfo** [comment]
+1

**Comment by tucotuco** [comment]
Implemented in 9dfa3516d1699065eb32999426cca433d6146b54

**Comment by tucotuco** [comment]
Passed public comment.

**Comment by tucotuco** [comment]
Ratified! Closing.
