### ISSUE TITLE
Term details show incorrect histories

### ISSUE THREAD

**Issue by tucotuco** [tdwg/chrono#35]
Examples (not necessarily an exhaustive list):

http://rs.tdwg.org/chrono/terms/version/earliestChronometricAge-2021-01-26.htm shows that it replaces http://rs.tdwg.org/chrono/terms/version/minimumChronometricAge-2020-11-17 whereas it should replace http://rs.tdwg.org/chrono/terms/version/maximumChronometricAge-2020-11-17

http://rs.tdwg.org/chrono/terms/version/latestChronometricAge-2021-01-26.htm shows that it replaces http://rs.tdwg.org/chrono/terms/version/maximumChronometricAge-2020-11-17 whereas it should replace http://rs.tdwg.org/chrono/terms/version/minimumChronometricAge-2020-11-17

http://rs.tdwg.org/chrono/terms/minimumChronometricAge shows that it is replaced by http://rs.tdwg.org/chrono/terms/earliestChronometricAgeReferenceSystem whereas it should be replaced by http://rs.tdwg.org/chrono/terms/latestChronometricAge

http://rs.tdwg.org/chrono/terms/maximumChronometricAge shows that it is replaced by http://rs.tdwg.org/chrono/terms/latestChronometricAge whereas it should be replaced by http://rs.tdwg.org/chrono/terms/earliestChronometricAge

**Comment by baskaufs** [comment]
@tucotuco There's a pull request to fix this that you should have been notified about

**Comment by tucotuco** [comment]
Looks good in production. Closing. Thank you!
