### ISSUE TITLE
New term to separate uncalibrated ages from verbatim

### ISSUE THREAD

**Issue by lbrensk** [tdwg/chrono#6]
After some discussion, we (Kitty Emery, Neil Wallis, Michelle LeFebvre, Rob Guralnick, John Wieczorek, and myself) have decided that we should create a new term called uncalibratedChronometricAge (working name right now) to separate out uncalibrated, raw ages that are the outputs of dating assays from everything else that may potentially go in a verbatimChronometricAge field. The current definition of verbatimChronometricAge encompasses both.

verbatimChronometricAge: [current definition] The verbatim age for a specimen, whether reported by a dating assay, associated references, or legacy information. For example, this could be the conventional radiocarbon age as given in an AMS dating report. This could also be simply what is reported as the age of a specimen in legacy collections data.

This would possibly change to:

uncalibratedChronometricAge: [new definition] The output of a dating assay before it is calibrated into an age using a specific conversion protocol.

verbatimChronometricAge: [new definition] The original description of age for a specimen.

The purpose of this is to allow uncalibrated ages to be more easily found if users want them since these are basically the raw output of a dating assay. However, we do still want the verbatimChronometricAge term because 1) it was viewed as important by the community during the Darwin Core Hour and 2) it allows legacy data, verbatim date ranges, etc. from collections to be reported.

**Comment by visead** [comment]
Sounds useful for quickly separating out calibrated and uncalibrated ages for aggregation or modelling, or re-running batch calibration of radiocarbon dates. 

Would the field be for _any_ uncalibrated age derived by radiometric dating (e.g. Ar/Ar, K/Ar), or just 14C? What are your thoughts on where ages derived from methods which don't really equate to calendar years should be stored? Or do we assume an OSL date is in 'real' years and put it in verbatimChronometricAge?

We know that many dating methods technically don't equate to calendar years, but the large errors and long time periods tend to negate the issue. In SEAD we have simply equated anything non-radiocarbon with calendar for research simplicity. However, non-palaeo users of the data are often confused when we tell them there is more than one way to measure time...

**Comment by lbrensk** [comment]
Yes, this would be for any uncalibrated age derived by radiometric dating. The specific dating method used can be reported in chronometricAgeProtocol and the method used to convert it into years (if this was done) can be reported in chronometricAgeConversionProtocol. All of this information together should give data users the ability to assess a given age more thoroughly, especially if an accompanying citation is given in the chronometricAgeReferences.

verbatimChronometricAge is more of a freeform textual field that the collections community wanted. It allows any verbatim information from a collections management database to be reported, even if the data provider doesn't know much about the provenance of where this age information came from (i.e. legacy data).

**Comment by tucotuco** [comment]
chrono:uncalibratedChronometricAge added.
