### ISSUE TITLE
Add Jekyll files for Quick Reference Guide

### ISSUE THREAD

**Issue by tucotuco** [tdwg/chrono#8]

**Comment by peterdesmet** [comment]
This is now done in 822074d82279ac9a4182c28d5fe3e47f59a3aa63. Website will be live at https://tdwg.github.io/chrono

Some review is required though:

- [ ] Review and extend the [homepage document](https://github.com/tdwg/chrono/blob/master/docs/index.md)
- [ ] Review title and maybe enable description (only visible in metadata) in [_config.yml](https://github.com/tdwg/chrono/blob/master/docs/_config.yml)
- [ ] Make sure correct links are used in repo README. Currently references chrono.tdwg.org, but that domain has not been set up
- [ ] The site looks very TDWG official: indicate clearly that this is something under review

**Comment by tucotuco** [comment]
OK. I have prepped the links to use https://tdwg.github.io/chrono temporarily in place of the eventually-anticipated https://chrono.tdwg.org/. I believe that takes care of this issue. Closing.
